"""Ack-faithful ghost-table replay for relay captures (shared by the replay
tools).

WHY THIS EXISTS (WAVE-23): the s2c stream in a relay capture was generated by
the SERVER against the REAL client's acks, which ride the c2s dnet headers
(lastSeqRecvd + ackMask; dnet.cc handleNotify). Whether a ghost record is a
CREATE (classId on the wire) or an UPDATE (no classId) is decided purely by
table state on each side -- and the server only commits a packet's ghost
creates/removes into its view of the client when the ack bit for THAT packet
comes back set. When the real client NACKed a packet (e.g. the pre-fix client
choking on the ShapeBase sound-thread polarity bug), the server re-marked the
ghost states dirty and RE-SENT the creates in later packets (netGhost.cc
notifyDropped / GhostInfo NotYetGhosted). A replay that commits every cleanly
decoded packet therefore diverges from the real table: it parses the re-sent
create as an update and shreds the rest of the section (combat_session.jsonl
line 4119+ was exactly this).

The fix mirrors the server's notify machinery: STAGE each s2c DATA packet's
ghost-table diff, then read the real client's verdict from the c2s ack stream
-- ACK keeps the diff, NACK rolls it back. Captures with no c2s lines never
deliver verdicts, so every diff stays applied: identical to the historical
commit-on-clean-decode behavior.

This models the CLIENT table only (ghost id -> class id). Guaranteed events
re-sent after a NACK are already handled by EventManager's ordered-seq
duplicate filter, and datablocks are transferred before ghosting starts.
"""
from aotbot.bitstream import BitStream
from aotbot import protocol_constants as pc


def parse_dnet_header(data: bytes):
    """Parse a connection packet's dnet header.

    Returns (seq, ack_start, ptype, ack_bits, ack_mask) -- widths per
    protocol_constants (1|1|9|9|2|3|ackByteCount*8, dnet.cc
    buildSendPacketHeader)."""
    bs = BitStream(data)
    bs.read_flag()
    bs.read_int(pc.PACKET_HEADER_CONNECT_SEQ_BITS)
    seq = bs.read_int(pc.PACKET_HEADER_SEQ_BITS)
    ack_start = bs.read_int(pc.PACKET_HEADER_ACK_START_BITS)
    ptype = bs.read_int(pc.PACKET_HEADER_TYPE_BITS)
    abc = bs.read_int(pc.PACKET_HEADER_ACK_BYTE_COUNT_BITS)
    mask = bs.read_int(8 * abc) if abc else 0
    return seq, ack_start, ptype, 8 * abc, mask


class GhostAckTracker:
    """Stage per-packet ghost-table diffs; commit/rollback on the c2s verdict.

    ``table`` is the live ``ph._ghost_classes`` dict, mutated in place. Usage:

        tracker = GhostAckTracker(ph._ghost_classes)
        # c2s connection packet:   tracker.on_c2s(raw_bytes)
        # before each s2c body:    before = tracker.snapshot()
        # after each s2c body:     tracker.stage(seq, before)
    """

    _SEQ_MASK = (1 << pc.PACKET_HEADER_SEQ_BITS) - 1

    def __init__(self, table: dict):
        self.table = table
        self.pending: dict[int, dict] = {}  # 9-bit s2c seq -> {gid: old | None}
        self._ack_start = None              # last c2s lastSeqRecvd processed

    def snapshot(self) -> dict:
        return dict(self.table)

    def stage(self, seq: int, before: dict) -> None:
        """Record the diff the just-decoded s2c packet ``seq`` applied."""
        diff = {}
        for gid in before.keys() | self.table.keys():
            if before.get(gid) != self.table.get(gid):
                diff[gid] = before.get(gid)
        key = seq & self._SEQ_MASK
        if diff:
            self.pending[key] = diff
        else:
            # A re-staged seq (9-bit wrap) with no diff: any stale entry is
            # long-decided; drop it rather than let a far-future verdict hit it.
            self.pending.pop(key, None)

    def on_c2s(self, data: bytes) -> None:
        """Process one c2s connection packet's ack info (server handleNotify).

        The server walks every s2c seq from its last notified position up to
        this packet's lastSeqRecvd exactly once; bit (lastSeqRecvd - i) of the
        ack mask says delivered (1) or dropped (0). Dropped -> the real client
        never committed that packet's ghost diff -> roll ours back."""
        try:
            _seq, ack_start, ptype, ack_bits, mask = parse_dnet_header(data)
        except Exception:
            return
        if ptype >= 3:
            return
        if self._ack_start is None:
            self._ack_start = ack_start
            return
        delta = (ack_start - self._ack_start) & self._SEQ_MASK
        if delta > 64:  # out-of-window jump (capture gap); drop stale pendings
            self._ack_start = ack_start
            self.pending.clear()
            return
        for d in range(delta):
            s = (self._ack_start + 1 + d) & self._SEQ_MASK
            bit = (ack_start - s) & self._SEQ_MASK
            delivered = bit < ack_bits and (mask >> bit) & 1
            diff = self.pending.pop(s, None)
            if diff is not None and not delivered:
                for gid, old in diff.items():
                    if old is None:
                        self.table.pop(gid, None)
                    else:
                        self.table[gid] = old
        self._ack_start = ack_start
